{
 "title": "2. Kubernetes Cluster Health",
 "description": "-",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "total",
    "query": {
     "query": "query_result(count(node_uname_info{cluster=~\"$cluster\",job=\"node-exporter\"}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node Not Ready",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{cluster=\"$cluster\",condition=\"Ready\",status!=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes Unschedulable",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\",phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Alertmanager Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count:up1{cluster=\"devneakscluster01\",job=\"prometheus-kube-prometheus-alertmanager\"}"
    }
   ]
  },
  {
   "title": "Alerts Pending",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{cluster=\"$cluster\",alertstate=\"pending\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  },
  {
   "title": "Alerts Firing",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{cluster=\"$cluster\",alertstate=\"firing\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  },
  {
   "title": "Node Disk Pressure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{cluster=\"$cluster\",condition=\"DiskPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Node Memory Pressure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{cluster=\"$cluster\",condition=\"MemoryPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Prometheus Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count:up1{cluster=\"$cluster\",job=\"prometheus-kube-prometheus-prometheus\"}"
    }
   ]
  },
  {
   "title": "Pending Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\",phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Crashlooping Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(increase(kube_pod_container_status_restarts_total{cluster=\"$cluster\"}[1h]) > 5)"
    }
   ]
  },
  {
   "title": "All Node Overview [Cluster: $cluster, Total: $total]",
   "type": "table",
   "description": "Partition utilization, disk read, disk write, download bandwidth, upload bandwidth, if there are multiple network cards or multiple partitions, it is the value of the network card or partition with the highest utilization rate collected.\n\nCurrEstab: The number of TCP connections whose current status is ESTABLISHED or CLOSE-WAIT.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_uname_info{cluster=~\"$cluster\",job=\"node-exporter\"} - 0",
     "legendFormat": "Hostname"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{cluster=~\"$cluster\",job=\"node-exporter\"})by(instance)",
     "legendFormat": "Run time"
    },
    {
     "expr": "node_memory_MemTotal_bytes{cluster=~\"$cluster\",job=\"node-exporter\"} - 0",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "count(node_cpu_seconds_total{cluster=~\"$cluster\",job=\"node-exporter\",mode='system'}) by (instance)",
     "legendFormat": "CPU"
    },
    {
     "expr": "node_load5{cluster=~\"$cluster\",job=\"node-exporter\"}",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{cluster=~\"$cluster\",job=\"node-exporter\",mode=\"idle\"}[5m])) by (instance)) * 100",
     "legendFormat": "CPU Used%"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{cluster=~\"$cluster\",job=\"node-exporter\"}-\nnode_memory_MemAvailable_bytes{cluster=~\"$cluster\",job=\"node-exporter\"}) / node_memory_MemTotal_bytes{cluster=~\"$cluster\",job=\"node-exporter\"} * 100",
     "legendFormat": "Mem used%"
    },
    {
     "expr": "max((node_filesystem_size_bytes{cluster=~\"$cluster\",job=\"node-exporter\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{cluster=~\"$cluster\",job=\"node-exporter\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {cluster=~\"$cluster\",job=\"node-exporter\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{cluster=~\"$cluster\",job=\"node-exporter\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{cluster=~\"$cluster\",job=\"node-exporter\",fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "分区使用率"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{cluster=~\"$cluster\",job=\"node-exporter\"}[5m])) by (instance)",
     "legendFormat": "最大读取"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{cluster=~\"$cluster\",job=\"node-exporter\"}[5m])) by (instance)",
     "legendFormat": "最大写入"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{cluster=~\"$cluster\",job=\"node-exporter\"} - 0",
     "legendFormat": "连接数"
    },
    {
     "expr": "node_sockstat_TCP_tw{cluster=~\"$cluster\",job=\"node-exporter\"} - 0",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{cluster=~\"$cluster\",job=\"node-exporter\"}[5m])*8) by (instance)",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{cluster=~\"$cluster\",job=\"node-exporter\"}[5m])*8) by (instance)",
     "legendFormat": "上传带宽"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum((1 - avg(rate(node_cpu_seconds_total{cluster=~\"$cluster\",job=\"node-exporter\",mode=\"idle\"}[5m])) by (instance)) * 100) by (instance)"
    }
   ]
  },
  {
   "title": "Mamory %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum((node_memory_MemTotal_bytes{cluster=~\"$cluster\",job=\"node-exporter\"}-\r\nnode_memory_MemAvailable_bytes{cluster=~\"$cluster\",job=\"node-exporter\"}) / node_memory_MemTotal_bytes{cluster=~\"$cluster\",job=\"node-exporter\"} * 100) by (instance)"
    }
   ]
  }
 ]
}