{
 "title": "Usages Report",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster" },
   { "name": "totalgpu", "query": "160" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(exported_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilisation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cluster:node_cpu:ratio_rate5m{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum{cluster=\"$cluster\"}) / sum(node_memory_MemTotal_bytes{job=\"node-exporter\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "GPU Utilisation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_namespace!=\"\"}) / count(DCGM_FI_DEV_GPU_UTIL)"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) "
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "GPU Allocated by Namespaces (Cluster)  | Total GPU : $totalgpu",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_namespace!=\"\"}) by (exported_namespace)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "GPU Uses by Reservation Type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 3 },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_namespace!=\"\"} * on (pod) group_left() (kube_pod_info{namespace=\"gpu-operator\",created_by_name=\"nvidia-dcgm-exporter\"} * on (node) group_left() kube_node_labels{label_super_cluster_usage!=\"OnDemand\"}))",
     "legendFormat": "Reserved Usages"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_namespace!=\"\"} * on (pod) group_left() (kube_pod_info{namespace=\"gpu-operator\",created_by_name=\"nvidia-dcgm-exporter\"} * on (node) group_left() kube_node_labels{label_super_cluster_usage=\"OnDemand\"}))",
     "legendFormat": "OnDemand Usages"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{} * on (pod) group_left() (kube_pod_info{namespace=\"gpu-operator\",created_by_name=\"nvidia-dcgm-exporter\"} * on (node) group_left() kube_node_labels{label_super_cluster_usage!=\"OnDemand\"}))",
     "legendFormat": "Reserved GPUs"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{} * on (pod) group_left() (kube_pod_info{namespace=\"gpu-operator\",created_by_name=\"nvidia-dcgm-exporter\"} * on (node) group_left() kube_node_labels{label_super_cluster_usage=~\"OnDemand\"}))",
     "legendFormat": "OnDemand GPUs"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "GPU User by Node",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_info{namespace=\"gpu-operator\",created_by_name=\"nvidia-dcgm-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", container!=\"\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}